export const keywords = [
  'thermoking',
  'thermo',
  'king',
  'thermo king',
  'liderkit',
  'fibrasil',
  'lider kit',
  'thermoking',
  'carrocerias',
  'importadas',
  'carrocerias importadas',
  'carrocerias termicas',
  'termicas',
  'equipamiento',
  'isotermos',
  'camiones',
  'transporte',
  'carretero',
  'camiones termicos',
  'furgones',
  'furgones termicos',
  'furgones uruguay',
  'transporte carretero',
  'uruguay',
  'thermoking uruguay',
  'thermo king uruguay',
  'reci',
  'importaciones',
  'reci importaciones',
  'servicio',
  'tecnico',
  'técnico',
  'service',
  'service thermoking',
  'servicio oficial',
  'oficial',
  'servicio thermo king',
  'servicio thermoking',
  'servicio tecnico thermoking',
  'rampas hidraulicas',
  'rampas',
  'hidraulicas',
];
